install:
	sudo pip3 install -r requirements.txt

run:
	FLASK_ENV=development FLASK_DEBUG=0 FLASK_APP=app.py flask run

debug:
	FLASK_ENV=development FLASK_DEBUG=1 FLASK_APP=app.py flask run --host=0.0.0.0

host:
	FLASK_ENV=development FLASK_DEBUG=0 FLASK_APP=app.py flask run --host=0.0.0.0
